on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Build Logseq SPA
        uses: logseq/publish-spa@v0.3.1
        with:
          graph-directory: .
          output-directory: www
          version: 0.10.6

      - name: Add .nojekyll
        run: touch www/.nojekyll

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: www

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
