name: Build & Publish Logseq SPA

on:
  push:
    branches:
      - main

permissions:
  contents: read        # we only need to read your source
  pages: write          # permission to publish to GitHub Pages
  id-token: write       # needed by deploy-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your repository
      - uses: actions/checkout@v4

      # 2) Build the Logseq SPA into ./www
      - name: Build Logseq SPA
        uses: logseq/publish-spa@v0.3.1
        with:
          graph-directory: .
          output-directory: www
          version: 0.10.6

      # 3) Prevent Jekyll from messing with files
      - name: Add .nojekyll
        run: touch www/.nojekyll

      # 4) Tell GitHub “we’re about to push a Pages site”
      - uses: actions/configure-pages@v3

      # 5) Upload the compiled site (uses the new Pages artifact action)
      - uses: actions/upload-pages-artifact@v2
        with:
          path: www

      # 6) Deploy the artifact to GitHub Pages
      - uses: actions/deploy-pages@v1
